### ISSUE TITLE
인덱스의 노드, 페이지 개념의 차이

### ISSUE THREAD

**Issue by polarHub25** [CSInterviewOrg/Interview_Study#10]

**Comment by pawoo0211** [comment]
인덱스 노드: B-Tree, B+ 트리에서의 기본 단위로 인덱스에서는 루트 노드, 내부 노드, 리프 노드로 표현됩니다. 이러한 노드는 논리적 단위이며 인덱스에서의 노드는 페이지를 포함하거나 페이지를 가리키는 포인터 역할을 합니다.
인덱스 페이지: 데이터베이스 시스템에서 데이터를 저장하는 기본 단위를 페이지로 표현합니다. 이러한 페이지는 디스크의 기본 단위이며 데이터가 실제로 저장되는 물리적 저장 단위입니다. 인덱스에서 페이지는 인덱스의 key:value 데이터를 저장하는 단위입니다.
