### ISSUE TITLE
스트림 중간 연산과 최종 연산

### ISSUE THREAD

**Issue by keongmini** [CSInterviewOrg/Interview_Study#4]

**Comment by pawoo0211** [comment]
중간 연산: 기존의 스트림을 다른 스트림으로 변환하도록 하는 연산
- 지연 실행 방식으로 동작 됨 -> 최종 연산을 실행하기 전까지 연산되지 않으며 최종 연산을 실행할 때 다른 스트림으로 변환 됨
- 연쇄적으로 사용 가능(체이닝 방식 사용 가능)
- 예시: filtered, map, distinct ..

최종 연산: 스트림을 처리한 후 결과를 반환하거나 스트림의 각 요소에 특정 작업을 진행하는 연산을 말함
- 즉시 실행 방식으로 동작
- 최종 연산이 실행되면 각 스트림의 원소가 적용되며 이에 따라 재사용이 불가능함
- 예시: collect, foreach, count..
