### ISSUE TITLE
일급 컬렉션

### ISSUE THREAD

**Issue by keongmini** [CSInterviewOrg/Interview_Study#5]
[일급 컬렉션 (First Class Collection)의 소개와 써야할 이유](https://jojoldu.tistory.com/412)

**Comment by pawoo0211** [comment]
일급 컬렉션이란 Collection 클래스를 멤버 변수로 가지는 하나의 클래스 래핑(Wrapping) 하는 클래스를 말합니다.
- 일급 컬렉션은 Collection 멤버 변수가 아닌 다른 멤버 변수를 가지면 안됨

Collection이라는 클래스에서 알 수 있듯이 Collection 클래스는 자료구조와 밀접한 클래스입니다. Collection 클래스에서 제공 되는 메서드는 기본 메서드이기에 Collection 멤버 변수에 따른 비즈니스 로직을 처리할 경우 이에 따른 비즈니스 로직을 따로 만들어야 합니다. 이렇게 비즈니스 로직을 만들 경우 공통적인 비즈니스 로직은 Collection 멤버 변수를 사용할 때마다 중복 코드가 발생하는데, 일급 컬렉션을 사용할 경우 이러한 중복 코드를 제거할 수 있습니다. 결과적으로 자료구조 클래스를 한번 더 래핑해서 특정 비즈니스 단위에 따른 자료 구조로 사용하여 클린 코드 측면에서 이점이 있는 것이 일급 컬렉션으로 볼 수 있는 것 같습니다.
