### ISSUE TITLE
방어적 복사

### ISSUE THREAD

**Issue by keongmini** [CSInterviewOrg/Interview_Study#6]

**Comment by pawoo0211** [comment]
방어적 복사란 원본 객체를 직접 반환하거나 참조하는 방식이 아닌 복사본을 반환하는 방식입니다. 방어적 복사를 하는 이유는 원본 객체의 상태 값을 변경하지 않기 위함인 객체 무결성을 유지하기 위함입니다.

이러한 방어적 복사와 깊은 복사는 유사하지만 엄밀한 차이점이 있습니다. 방어적 복사는 객체의 특정 필드 값에 대해서 복사본을 반환하며 가끔은 객체 자체에 대한 복사본을 반환하는 경우도 있습니다. 하지만 깊은 복사는 객체가 참조하는 객체까지 모든 복사본을 만들어 반환하는 것에 차이점이 있습니다.
